name: CI Test

on:
  pull_request:
    branches:
      - "**"

jobs:
  Continuous-Integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        run: npm install -g pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: prettier format check
        run: |
          npm run format:check
      - name: lint check
        run: |
          npm run lint
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build test
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: blockx3/payko:latest
          platforms: linux/amd64
